"""Build an executable per-variant report notebook from saved artifacts.

Usage:
    python -m pls_explorer.notebook_report --variant baseline
        → notebooks/reports/baseline.ipynb (executed in-place)

Or programmatically:
    from pls_explorer.notebook_report import build_and_execute
    build_and_execute(['baseline', 'row_normalized', 'autoscaled', 'pareto'])
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

import nbformat as nbf

from .config import REPO_ROOT


def _md(src: str):
    return nbf.v4.new_markdown_cell(src)


def _code(src: str):
    return nbf.v4.new_code_cell(src)


def build_notebook(variant: str) -> nbf.NotebookNode:
    """Return a fresh notebook for one variant. Not yet executed."""
    nb = nbf.v4.new_notebook()
    cells = [
        _md(f"# Variant report: `{variant}`\n\n"
            "Loads saved artifacts and displays the headline figures inline.\n"
            "Generated by `pls_explorer.notebook_report`."),

        _code(
            "import json\n"
            "from pathlib import Path\n\n"
            "import numpy as np\n"
            "import pandas as pd\n"
            "import plotly.io as pio\n"
            "pio.renderers.default = 'notebook_connected'\n\n"
            "from pls_explorer import viz\n"
            "from pls_explorer.config import RESULTS_DIR\n\n"
            f"VARIANT = {variant!r}\n"
            "ROOT = RESULTS_DIR / VARIANT\n"
            "print('Reading:', ROOT)"
        ),

        _md("## Headline numbers"),
        _code(
            "metrics = {}\n"
            "for lab in ['real', 'null1', 'null2']:\n"
            "    with open(ROOT / lab / 'metrics.json') as f:\n"
            "        metrics[lab] = json.load(f)\n"
            "rows = []\n"
            "for lab, m in metrics.items():\n"
            "    rows.append({\n"
            "        'target': lab,\n"
            "        'n_comp': m['n_components'],\n"
            "        'Q²': round(m['q2_global'], 3),\n"
            "        'RMSECV': round(m['rmsecv'], 3),\n"
            "        'RMSECV/RMSEC': round(m['rmsecv_over_rmsec'], 3),\n"
            "        'diagonality': round(m['w_structure']['diagonality_index'], 4),\n"
            "        'off-diag entropy': round(m['w_structure']['off_diagonal_entropy'], 3),\n"
            "        '||B||_F': round(m['w_structure']['frobenius_norm'], 3),\n"
            "        'perm p': m.get('permutation_p_value', float('nan')),\n"
            "    })\n"
            "summary = pd.DataFrame(rows).set_index('target')\n"
            "summary"
        ),

        _md("## Component selection"),
        _code(
            "sel_path = ROOT / 'component_selection.json'\n"
            "if sel_path.exists():\n"
            "    sel = json.load(open(sel_path))\n"
            "    print('one_sigma →', sel['selection']['one_sigma'])\n"
            "    print('van_der_voet →', sel['selection']['van_der_voet'])\n"
            "    print('chosen →', sel['selection']['chosen'])\n"
            "    fig = viz.plot_rmsecv_components(\n"
            "        sel['grid'], sel['q2'], sel['rmsecv'], sel['rmsec'],\n"
            "        chosen_ncomp=sel['selection']['chosen'],\n"
            "        title=f'{VARIANT}: component selection')\n"
            "    fig.show()\n"
            "else:\n"
            "    print('No component selection sweep saved (n_components forced).')"
        ),

        _md("## Deliverable: 3-way B comparison (real vs Null-1 vs Null-2)"),
        _code(
            "B_real = np.load(ROOT / 'real' / 'B.npy')\n"
            "B_null1 = np.load(ROOT / 'null1' / 'B.npy')\n"
            "B_null2 = np.load(ROOT / 'null2' / 'B.npy')\n"
            "diag = {lab: metrics[lab]['w_structure']['diagonality_index']\n"
            "        for lab in ['real', 'null1', 'null2']}\n"
            "viz.plot_W_3way(B_real, B_null1, B_null2, diagonality=diag,\n"
            "                title=f'{VARIANT}: B matrix — real | Null-1 mult | Null-2 random').show()"
        ),

        _md("## Outer-product loadings (LV 1) — real fit\n\n"
            "Marginal skyline bars colored by glomerular NMF cluster (X side) and "
            "by odorant NMF cluster (Y side)."),
        _code(
            "from pls_explorer.data import load_paired\n"
            "data = load_paired(metrics['real']['config']['data_variant'])\n"
            "loadings = dict(np.load(ROOT / 'real' / 'loadings.npz'))\n\n"
            "class PLSStub:\n"
            "    pass\n"
            "stub = PLSStub()\n"
            "stub.x_loadings_ = loadings['x_loadings']\n"
            "stub.y_loadings_ = loadings['y_loadings']\n\n"
            "viz.plot_outer_product_marginals(\n"
            "    stub, component=0,\n"
            "    x_group_labels=data.glom_clusters,\n"
            "    y_group_labels=data.glom_clusters,\n"
            "    title=f'{VARIANT}: outer-product LV 1, real fit').show()"
        ),

        _md("## Permutation null distribution"),
        _code(
            "perm_path = ROOT / 'real' / 'permutation.npz'\n"
            "if perm_path.exists():\n"
            "    p = np.load(perm_path)\n"
            "    fig = viz.plot_permutation_null(\n"
            "        q2_null=p['q2_null'], q2_observed=float(p['q2_observed']),\n"
            "        p_value=float(p['p_value']),\n"
            "        title=f'{VARIANT}: permutation null on real Y')\n"
            "    fig.show()\n"
            "else:\n"
            "    print('No permutation results saved.')"
        ),

        _md("## VIP scores (real fit)"),
        _code(
            "vip = np.load(ROOT / 'real' / 'VIP.npy')\n"
            "B_real = np.load(ROOT / 'real' / 'B.npy')\n"
            "B_sign = np.sign(B_real.sum(axis=1))\n"
            "vip_ci_path = ROOT / 'real' / 'VIP_ci.npz'\n"
            "vip_ci = None\n"
            "if vip_ci_path.exists():\n"
            "    z = np.load(vip_ci_path)\n"
            "    vip_ci = (z['vip_ci_low'], z['vip_ci_high'])\n"
            "viz.plot_vip_bars(vip, B_sign=B_sign, vip_ci=vip_ci, top_n=40,\n"
            "                  title=f'{VARIANT}: top 40 VIP gloms (real)').show()"
        ),

        _md("## Per-glomerulus Q² (real fit)"),
        _code(
            "q2_col = np.load(ROOT / 'real' / 'per_glom_q2.npy')\n"
            "from pls_explorer.data import load_paired\n"
            "data = load_paired(metrics['real']['config']['data_variant'])\n"
            "viz.plot_per_glom_q2_heatmap(q2_col, glom_clusters=data.glom_clusters,\n"
            "                              title=f'{VARIANT}: per-glom Q² (sorted by cluster)').show()"
        ),

        _md("## Worst-predicted odorants (real fit)"),
        _code(
            "Y_hat = np.load(ROOT / 'real' / 'y_hat_oof.npy')\n"
            "Y_true = data.Y.to_numpy(dtype=float)\n"
            "import pls_explorer.preprocess as pp\n"
            "if metrics['real']['config']['log_transform']:\n"
            "    Y_true = pp.log1p_positive(Y_true)\n"
            "if metrics['real']['config']['row_normalize']:\n"
            "    Y_true = pp.row_l2_normalize(Y_true)\n"
            "X_pp = data.X.to_numpy(dtype=float)\n"
            "if metrics['real']['config']['log_transform']:\n"
            "    X_pp = pp.log1p_positive(X_pp)\n"
            "if metrics['real']['config']['row_normalize']:\n"
            "    X_pp = pp.row_l2_normalize(X_pp)\n"
            "odorant_names = data.odorants['Name'].iloc[\n"
            "    data.X.index.get_level_values('odorant').astype(int).to_numpy()].tolist()\n"
            "viz.plot_worst_predicted(X_pp, Y_true, Y_hat, odorant_names,\n"
            "                          n_worst=6,\n"
            "                          title=f'{VARIANT}: worst-predicted odorants').show()"
        ),

        _md("## R²X and R²Y cumulative per component (real fit)"),
        _code(
            "import plotly.graph_objects as go\n"
            "r2x = metrics['real']['r2x_cumulative']\n"
            "r2y = metrics['real']['r2y_cumulative']\n"
            "ncomps = list(range(1, len(r2x)+1))\n"
            "fig = go.Figure()\n"
            "fig.add_trace(go.Scatter(x=ncomps, y=r2x, mode='lines+markers', name='R²X cumulative'))\n"
            "fig.add_trace(go.Scatter(x=ncomps, y=r2y, mode='lines+markers', name='R²Y cumulative'))\n"
            "fig.update_layout(title=f'{VARIANT}: variance explained per component (real)',\n"
            "                   xaxis_title='n_components', yaxis_title='cumulative R²',\n"
            "                   template='plotly_white', width=720, height=420)\n"
            "fig.show()"
        ),
    ]
    nb["cells"] = cells
    nb["metadata"] = {
        "kernelspec": {"name": "python3", "display_name": "Python 3",
                       "language": "python"},
        "language_info": {"name": "python", "version": "3.11"},
    }
    return nb


def build_and_execute(variants: list[str], out_dir: Path | None = None) -> list[Path]:
    """Build and execute (in-place) one notebook per variant. Returns paths."""
    if out_dir is None:
        out_dir = REPO_ROOT / "notebooks" / "reports"
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    paths = []
    for v in variants:
        nb = build_notebook(v)
        path = out_dir / f"{v}.ipynb"
        with open(path, "w") as f:
            nbf.write(nb, f)
        print(f"[{v}] wrote {path}; executing…")
        rc = subprocess.call([
            "/opt/anaconda3/envs/castrolab-dev/bin/jupyter", "nbconvert",
            "--to", "notebook", "--execute", "--inplace",
            "--ExecutePreprocessor.timeout=180",
            str(path),
        ])
        if rc != 0:
            print(f"[{v}] WARNING: nbconvert returned {rc}")
        paths.append(path)
    return paths


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--variant", action="append", required=True,
                   help="Variant name (repeatable)")
    args = p.parse_args()
    build_and_execute(args.variant)


if __name__ == "__main__":
    main()
